    function myFunction()
    {
alert("Im excited to improve my programming skills this year. Can't wait to use everything I learn in INF 370")
    }

function myFunction17() {
  alert("I am excited about the new teaching and assessment methods and 354 means I am closer to finishing my degree.");}

function GabyAlert(){
  window.alert("I am excited for INF 354 because the coding I will learn here will greatly benefit me in INF 370.");
}
